version: '3'
services:
  service:
    container_name: ballotbox
    build: .
    environment:
        - BALLOT_OPTIONS=Chilli Pica, Delano, Gusto Blynai, Iki Mishraines
    volumes: 
        - ./code:/srv:rw
          #    ports:
          #        - 9000
    command: ["--reload", "--access-logfile=-"]

  auth: # authentication proxy for ballot box service
      build: auth_proxy
      volumes: 
        - ./auth_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./auth_proxy/htpasswd:/etc/nginx/.htpasswd:ro
      ports:
          - 80:80
      depends_on: 
        - "service"
