version: '3'
services:
    service: # ballot box service
        container_name: ballotbox
        build: .
        environment:
            - BALLOT_OPTIONS

    auth: # authentication proxy for ballot box service
      build: auth_proxy
      ports:
          - 9393:80
      depends_on: 
        - "service"

    
