version: '3'
services:
    ballotbox:
        container_name: ballotbox
        build: ballotbox
        environment:
            - BALLOT_OPTIONS
    web:
        build: webfront
        ports:
            - 80:80
        depends_on: 
            - "ballotbox"


