#! /bin/env python

from pathlib import Path
import requests
import string
import sys
import json


def make_ballot_webui(menu_options):
    ui_template = Path('webfront/webui/ballot.html.template').read_text()
    ui = string.Template(ui_template).safe_substitute(MENU_OPTIONS=menu_options)
    Path('webfront/webui/ballot.html').write_text(ui)

def start_services(ballot_options):
    import os, subprocess, json
    env_vars = dict(os.environ, BALLOT_OPTIONS = ballot_options)
    subprocess.run(['docker-compose', 'up', '--detach', '--build', '--force-recreate'], check=True, env=env_vars)

if __name__ == '__main__':
    if sys.stdin.isatty():
        print("No menu options on stdin, exititing", file=sys.stderr)
        sys.exit(1)
    menus_json = sys.stdin.read()
    if not menus_json:
        print("Got empty menu options on stdin", file=sys.stderr)
        sys.exit(2)
    print("Got menus for the day: {}".format(menus_json))
    menus = json.loads(menus_json)
    make_ballot_webui(menus)
    ballot_options = ','.join([m['restaurant_name'] for m in menus]) 
    start_services(ballot_options)
    print("Startded ballot with options: {}".format(ballot_options))

