version: '3'
services:
  ballotbox:
    build: .
    environment:
        - BALLOT_OPTIONS=Chilli Pica, Delano, Gusto Blynai, Iki Mishraines
    volumes: 
        - ./code:/srv:rw
    ports:
        - 80:8000
    command: ["--reload"]

